### ISSUE TITLE
Add function to add add public keys to all nodes

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/ovs-documentation#12]
In OVS setup there is a part to add public keys to the nodes for user `root` & `ovs`. 
This should be added to https://github.com/openvstorage/ovs-documentation/blob/master/Installation/geoscalegettingstarted.md#creating-cluster-fwk-optional

**Comment by wimpers** [comment]
@kinvaris can you create a PR for this?

**Comment by wimpers** [comment]
I'm not sure what is expected of this ticket. Exchanging the keys is already part of the OVS setup https://github.com/openvstorage/framework/blob/b187912a4ea93cd9f51ee6b44d23d6d685f1f394/ovs/lib/setup.py#L311 . What do you expect to be documented?

**Comment by wimpers** [comment]
@kinvaris see question above

**Comment by kinvaris** [comment]
This is not required anymore as we have the `setup.json` to our disposal
