### ISSUE TITLE
Only one crash dump per application is preserved

### ISSUE THREAD

**Issue by wimpers** [openvstorage/ovs-documentation#14]
_From @redlicha on July 1, 2016 10:23_

Together with this volumedriver bug https://github.com/openvstorage/volumedriver/issues/51 this prevents investigating the root cause of said bug (there's of course a tradeoff to be made of keeping enough history vs. filling the system up with crash dumps).

_Copied from original issue: openvstorage/framework#685_

**Comment by wimpers** [comment]
_From @khenderick on July 1, 2016 14:26_

@redlicha, what's expected on the framework? Is this a volumedriver settng we need to change?

**Comment by wimpers** [comment]
_From @redlicha on July 1, 2016 14:53_

@khenderick, my fuzzy, high level expectation is that the operating system (or more specifically apport) is configured to preserve a bigger number of core dumps.

**Comment by wimpers** [comment]
_From @khenderick on July 1, 2016 15:30_

@wimpers, I assume that is a request for documentation? Do we need a ticket here, or on some docs repo?

**Comment by wimpers** [comment]
@jtorreke @jeroenmaelbrancke @matthiasdeblock any idea how you configure this in the OS?

**Comment by jtorreke** [comment]
If you put this in /etc/sysctl.conf, you should be able to differentiate in core dumps:

```
kernel.core_pattern=/mnt/sandboxtmp/coredumps/core-%e-%p-%t
kernel.core_uses_pid=1
```

Execute _sysctl -p_ afterwards to load the settings.

**Comment by redlicha** [comment]
@jtorreke , does that also work with apport, as the crash dumps we saw (CMIIW, @kinvaris ) were generated by it?

**Comment by jtorreke** [comment]
@redlicha It should work, although I haven't tested this:
https://wiki.ubuntu.com/Apport#How_does_it_work_internally.3F

**Comment by redlicha** [comment]
Great, thanks!

**Comment by redlicha** [comment]
Can we please make sure that this is implemented for our installations?
Or, since in the mean time ran multiple times into the problem of apport-unpack taking very long for even small crash dumps, avoid using apport altogether?

**Comment by redlicha** [comment]
Data point: trying to unpack a core dump (on an NVMe device):
```
du -h _usr_bin_volumedriver_fs.0.crash-5 
65M	_usr_bin_volumedriver_fs.0.crash-5

time apport-unpack _usr_bin_volumedriver_fs.0.crash-5 unpacked
^Z
[1]+  Stopped                 apport-unpack _usr_bin_volumedriver_fs.0.crash-5 unpacked

real	94m4.884s
user	0m0.000s
sys	0m0.000s
```
