### ISSUE TITLE
How to setup a virtualized Open vStorage environment

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/ovs-documentation#18]
* Setup a virtual machine with operating system `ubuntu 14.04`
* Make it possible for `root` to login
* Add other storage disks for roles & alba:
    * 4x alba disks, 5 gb each, via `SATA` diskbus in `QCOW` storage format. After creating them, add a UUID to the `serial number` field so that all alba disks are unique in the cluster.
    * 3x role disks, 10 gb each, via `SATA` diskbus in `QCOW` storage format. `['WRITE', 'READ', 'SCRUB']`
    * 1x `DB` disk, 50 gb, via `SATA` diskbus in `QCOW` storage format.
* Start the VM
* Start installing Open vStorage

**INFO:** The `QCOW` format enables you to snapshot volumes.

![](http://i.imgur.com/e96XX1Z.png)

**Comment by wimpers** [comment]
We will create these VMs for the customer so they can easily download them to play with.
