### ISSUE TITLE
CentOS installation documentation

### ISSUE THREAD

**Issue by bmikhael** [openvstorage/ovs-documentation#19]
I'm trying to install open vStorage on CentOS7, but it seems to be impossible!!!
Your repo at http://apt.openvstorage.org contains only .deb packages.
Can open vStorage be installed on any linux distribution but Debian family?!!!

**Comment by wimpers** [comment]
Hi, 

Open vStorage can be installed on CentOS7

-   Install wget
```
yum install wget -y
```
-   Currently there is a dependency on the Fedora 22 repo so add it also
```
echo '[fc22]
name=fc22
baseurl=https://download.fedoraproject.org/pub/fedora/linux/releases/22/Everything/x86_64/os
enabled=0' > /etc/yum.repos.d/fc22.repo
rpm --import 'https://pgp.mit.edu/pks/lookup?op=get&search=0x11ADC0948E1431D5'
```

-   Add the Open vStorage RPM repo
    - Latest stable version
```
echo '[openvstorage]
name=OVS repo
baseurl=http://yum.openvstorage.org/CentOS/7/x86_64/dists/fargo
enabled=1
gpgcheck=0' > /etc/yum.repos.d/ovs.repo
```
    - Latest experimental version
```
echo '[openvstorage]
name=OVS repo
baseurl=http://yum.openvstorage.org/CentOS/7/x86_64/dists/unstable
enabled=1
gpgcheck=0' > /etc/yum.repos.d/ovs.repo
```
-   First install the dependencies
```
yum install --nogpgcheck --enablerepo=fc22 librbd1 librados2 gcc volumedriver-server -y
```
-   Add the necessary external repos
```
wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo
wget -P /etc/yum.repos.d/ http://packages.efficios.com/repo.files/EfficiOS-RHEL7-x86-64.repo
```
-   Install the Open vStorage packages
```
yum install --nogpgcheck openvstorage -y
```
- As root, disable SELinux
```
setenforce 0
```

Do note that currently we have no ported the ASD manager (ALBA) to CentOS7.

**Comment by l1x** [comment]
Since Fedora 22 is archived the correct URL for the repo has changed.
```
echo '[fc22]
name=fc22
baseurl=http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/22/Everything/x86_64/os/
enabled=0' > /etc/yum.repos.d/fc22.repo
```

**Comment by samyang2558** [comment]
At present, most enterprises choose to use the Redhat and CentOS series, I hope to be able to centos the compatibility of the operating system, I am very optimistic about the software
