### ISSUE TITLE
Documentation does not state the the 'ovs' user must not be used prior to installing ovs

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/ovs-documentation#20]
# Problem description
Documentation does not state the the 'ovs' user must not be used prior to installing ovs
# Possible solution
Add an entry into the 'Install Ubuntu' where you clearly state that the user 'ovs' must not be used.
# Additional information
After having made the ovs user, you will not be able to install ovs:
https://github.com/openvstorage/framework/issues/802

**Comment by kinvaris** [comment]
`ovs` group should also be removed
