### ISSUE TITLE
Default qemu user has insufficient rights to access .raw in vPool

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/ovs-documentation#21]
## Problem description
Default qemu user has insufficient rights to access .raw in vPool.
This used to be documented but I couldn't find this anywhere.
## Possible solution
The qemu user must be added to the ovs group.
Add the following line to the installation of Ubuntu:
- usermod -a -G ovs libvirt-qemu

**Comment by wimpers** [comment]
This should be added to the Compute host section right?
