### ISSUE TITLE
Update add preset

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/ovs-documentation#29]
Update the image of add-preset because its outdated: https://github.com/openvstorage/ovs-documentation/blob/97c63b2baa909799bbc4f5fe18c01d215c5caac5/Administration/usingthegui/backends.md#user-content-presets

**Comment by wimpers** [comment]
https://github.com/openvstorage/ovs-documentation/commit/bd1957f4da801664910178136bedaba18fef26fc
