### ISSUE TITLE
Document flexible scrubber

### ISSUE THREAD

**Issue by wimpers** [openvstorage/ovs-documentation#36]
See https://github.com/openvstorage/framework/issues/1020#issuecomment-253736517

Setting the /ovs/framework/auto_scrub key to false will disable the automatic scrubbing.

**Comment by wimpers** [comment]
https://github.com/openvstorage/framework/issues/1067#issuecomment-255104307

**Comment by khenderick** [comment]
When documenting on how tasks can be disabled or rescheduled with the new global system, please only use keys in examples that are explained completely; e.g. what the impact could be of disabling or reconfiguring their frequency. This way we prevent people from just randomly changing scheduled for tasks that they might not fully understand.

**Comment by wimpers** [comment]
Already documented as part of https://openvstorage.gitbooks.io/framework/content/docs/scheduledtasks.html
