### ISSUE TITLE
Explain different roles more clearly

### ISSUE THREAD

**Issue by wimpers** [openvstorage/ovs-documentation#58]
Currently the topology (https://openvstorage.gitbooks.io/administration/content/Openvstorage/topology.html) is no longer in line with how the clusters are deployed. Now you assign one or more roles to a node (compute, storage, controller, voldrv).  

Remove performance node as we no longer use this.

**Comment by wimpers** [comment]
Better option would be to use config 1, 2, 3,4 ?

**Comment by yveskerwyn** [comment]
Thanks for also updating the devops gitbook, documenting the playbooks for each of the configs: https://openvstorage.gitbooks.io/devops/content/Docs/ansible.html

**Comment by wimpers** [comment]
A ticket under  dev_ops will be used for updating the dev_ops gitbook https://github.com/openvstorage/dev_ops/issues/44
