### ISSUE TITLE
iSCSI manager

### ISSUE THREAD

**Issue by wimpers** [openvstorage/ovs-documentation#69]
```
apt-get install openvstorage-iscsi-plugin
apt-get install iscsi-manager

```

iscsi-manager setup

**Comment by JeffreyDevloo** [comment]
The iscsi-manager can be installed independently from the framework ;)

**Comment by wimpers** [comment]
# Exposing a vDisks over iSCSI
Open vStorage allows to expose vDisks over iSCSI for seamless integration with Bare Metal servers or Virtual Machines. 


# Enterprise Edition
In the Open vStorage Enterprise Edition exposing a vDisk over iSCSI can be done from the GUI. There are 2 additional components which need to be installed:
* The iSCSI Manager: a small API for managing iSCSI servers and targets.
* The iSCSI Plugin: this plugin adds the necessary additional screens to the GUI.   

## The iSCSI Plugin
Install the iSCSI plugin on every host were the Framework is running.

´´´apt-get install openvstorage-iscsi-plugin´´´

Under Administration a new entry ´iSCSI Nodes´ will become available.

## The iSCSI Manager
On every server where you want to expose iSCSI disks, install the iSCSI Manager package. The iSCSI Manager can installed independent of the Open vStorage Framework and Storage Routers as it connects by means of the Edge to the vDisk.

´´´apt-get install iscsi-manager´´´

After installing the iSCSO Manager, execute the setup.

´´´iscsi-manager setup´´´

Go through the setup steps:
* Select the public IP address and port on which to expose the API.
* Configure the iSCSI portal information.

# Register the iSCSI nodes
Open the GUI and navigate to **Admnistration > iSCSI Nodes** and click the add iSCSI nodes button next to each server to register the nodes.

# Expose a vDisk
To expose a vDisk over iSCSI, navigate to the vDisk detail page and click the expose button under iSCSI Actions. Select the iSCSI Node on which to expose the vDisk pass the edge username and password.
Optionally an ACL can be supplied to indicate which IPs or networks are allowed to have access to the iSCSI disk.


# Open Source Edition 
In the Open Source Edition a vDisk can be exposed over iSCSI using the CLI. Note that the GUI integration is part of the Open vStorage EE version.

Install TGT and the Open vStorage TGT package. 
´´´
echo "deb http://apt.openvstorage.com unstable main" > /etc/apt/sources.list.d/ovsaptrepo.list
apt-get update
apt-get install tgt
apt-get install tgt-openvstorage
´´´

Create a new target device.

´´´tgtadm --lld iscsi --mode target --op new --tid=1 --targetname iqn.2016-01.com.openvstorage:for.all´´´

Add a logical unit (LUN)
´´´tgtadm --lld iscsi --op new --bstype openvstorage+tcp --mode logicalunit --tid 1 --lun 1 -b 10.100.188.31:26203/volumeName´´´

Replace 10.100.188.31 by the IP of the Storage Router on which the vPool is exposed containing the vDisk.
Replace 26203 by the edge port of the vPool on that Storage Router (see Storage Router detail page).
Replace volumeName by the name of the vDisk you want to expose. Note that the vDisk should already be created.

Execute ´tgt-admin -s´ to see if the vDisk is exposed. The result should be something like

´´´root@PHY-3N-188-31:~# tgt-admin -s
Target 1: iqn.2016-01.com.openvstorage:for.all
    System information:
        Driver: iscsi
        State: ready
    I_T nexus information:
    LUN information:
        LUN: 0
            Type: controller
            SCSI ID: IET     00010000
            SCSI SN: beaf10
            Size: 0 MB, Block size: 1
            Online: Yes
            Removable media: No
            Prevent removal: No
            Readonly: No
            SWP: No
            Thin-provisioning: No
            Backing store type: null
            Backing store path: None
            Backing store flags:
        LUN: 1
            Type: disk
            SCSI ID: IET     00010001
            SCSI SN: beaf11
            Size: 10737 MB, Block size: 512
            Online: Yes
            Removable media: No
            Prevent removal: No
            Readonly: No
            SWP: No
            Thin-provisioning: Yes
            Backing store type: openvstorage+tcp
            Backing store path: 10.100.188.31:26203/volumeName
            Backing store flags:
´´´
